apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: rabbitmq
    finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  project: messagebus
  source:
    repoURL: https://github.com/DiamondLightSource/messagebus
    path: charts/rabbitmq
    targetRevision: HEAD
  destination:
    namespace: messagebus
    name: argus
  ignoreDifferences:
    - kind: Secret
      name: rabbitmq-load-definition
      namespace: messagebus
      jqPathExpressions:
        - '.stringData."load_definition.json" | fromjson | .users[] | select(.name="user") | .password'
    - kind: Secret
      name: rabbitmq-certs
      namespace: messagebus
      jqPathExpressions:
        - '.data."ca.crt"'
        - '.data."tls.crt"'
        - '.data."tls.key"'
    - kind: Secret
      name: rabbitmq-erlang
      namespace: messagebus
      jqPathExpressions:
        - '.data."rabbitmq-erlang-cookie"'
    - kind: Secret
      name: rabbitmq
      namespace: messagebus
      jqPathExpressions:
        - '.data."rabbitmq-password"'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectingIgnoreDifferences=true
