apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgAda4T+sV9vcDApjvIBgUUjc+6BDxaDaCe0vYwXkDcvCahdav7azSWdNl1byzlZc0JuEReZtFXvC/fwFSBFod8ItfwlLV47PcF5T+MuiEPjGFCFbHt8vjrS7fMqC68GEkHQwGVPfdR+/enUOUsNgNHKXKlzOLmUKflG13cX5l1V32yeEf52HdTf8C5YKRyQ8+QL28E5xCQN56JyMRnhwnXINFwhvOKDZdmZMq1h6Fx3Vq6nRYO4KMGp55Qn1U5F8bxT/tskD9DnVhsJLaCIlms2QcmX7esweQ7e/Kuh0fx6p74dmcd3WaV+5XBQA7bW+Reo5QXZMaAkhbCnglz0F40J9xzMlHD02gEtK/2JnSvD+pEwL53zut3WucfIzqG1qAAafuJ26jPZn9LkI+UPbbFlz+Vp6WcD3z2nNsxoCRiw7iQoqtovZBjcAc5FBf+Fijd7yKRJR6aaZ4Kl3ZgUiTuUYONG944K3WtSOXy5oh2a+LzmBeViKtjow9yP2lDEU6AS55uiz4HhmvgWYIbPKZL3cQA5fDLdSNQe3wwUPgrdOI/KkWFe7KpgC120xSRCuBRrCqMh9lkvCeJFvC3K8ySNjfdy+HD9kDHuSHZw5n85p14ddZT9au80bZZ/KkSRb7N6qhgp++//3TQ311Va3hp5zHdIqNsI6DmvumApiQ/tgwo9EKvuql6Im+c/9lhzcbXkqQHrXu4SIL+pwQzgIrwvFrQ3PKGfGh0/PahXBohJ+Q==
