apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-load-definition
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  load_definition.json: |-
    {
      "users": [
        {
          "name": "user",
          "password": "{{ randAlphaNum 20 }}",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/",
          "description": "Default virtual host",
          "tags": [],
          "metadata": {
            "description": "Default virtual host",
            "tags": []
          }
        },
        {
          "name": "testing",
          "description": "An extra vhost for testing purposes",
          "tags": [],
          "metadata": {
            "description": "A vhost for testing",
            "tags": []
          }
        }
      ],
      "permissions": [
        {
          "user": "user",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }, 
        {
          "user": "user",
          "vhost": "testing",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ]
    }
